              - name: Ověření ve službě Google Cloud 
               používá: google-github-actions/auth@v2.1.3 
               deployd: 
               on:
               test:
               run:
               
